#!/bin/bash
# change openthinclient password dialog for openthinclient VM

pass=`zenity --title="openthinclient user password change" --text="Change the password of the default openthinclient user\n\ \n\
 The default password for this user is \"openthinclient\" \n\
 If you change the password please do not forget it" --entry --hide-text`
# exit if the user pressed the Cancel button
if [ $? = 1 ];
then exit 0
fi

# check if passwords are the same
pass2=`zenity --title="Retype it" --text="Re-type it" --entry --hide-text`
if [ "$pass" == "$pass2" -a "$pass" != "" ]; then
  OK=0
else
  zenity --error --title="Error" --text="Passwords do not match"
  exit 0
fi
# change password of openthinclient user
echo "openthinclient:$pass" | sudo chpasswd

if [ "$?" -eq "0" ]
then
    zenity --info --title="Updated" --text="The password was successfully updated\n"
else
    zenity --error --title="Update error" --text="password could not be updated. Please use the \"sudo passwd\" command" 
fi
