#!/bin/bash
# Filename:     openthinclient-restart
# Purpose:      restart the openthinclient server via start/stop action
#------------------------------------------------------------------------------

echo "Stopping service"
sudo service openthinclient-manager stop

# wait for shutdown
while lsof -i -n -P | grep 10389 &>/dev/null; do
        sleep 1
done

# workaround for proper port release
sudo killall nc &>/dev/null
sudo nc -l 0.0.0.0 10386 & echo ok | sudo nc 0.0.0.0 10386

sleep 5
echo "Starting service"
sudo service openthinclient-manager start

# wait a little to show status
sleep 3
systemctl is-active --quiet openthinclient-manager && echo Service is running again