#!/bin/bash
# Filename:     openthinclient-cleaner
# Purpose:      cleanup the openthinclient appliannce after initial build
#------------------------------------------------------------------------------


#------------------------------------------------------------------------------
# openthinclient specific cleanup


# make sure openthinclient server is stopped
/etc/init.d/openthinclient-manager stop
/etc/init.d/openthinclient-manager status

# remove nfs db from manager home
rm /home/openthinclient/otc-manager-home/nfs/nfs-paths.db*

# remove cache files
rm -rf /home/openthinclient/otc-manager-home/nfs/root/var/cache/archives/1/*
rm -rf /home/openthinclient/otc-manager-home/nfs/root/var/cache/archives/2/*

# remove homes
rm -rf 	/opt/openthinclient/server/default/data/nfs/home/*

# remove old logfiles from manager home
rm -rf /home/openthinclient/otc-manager-home/logs/*

# delete ldap backups
find /var/backups/openthinclient/ -name "*\.ldiff\.*" -type f | xargs rm

#------------------------------------------------------------------------------
# general cleanup

# remove udev network rules to cleanup old interfaces
echo "==> remove udev network rules to cleanup old interfaces"
if [ -f "/etc/udev/rules.d/70-persistent-net.rules" ]; then
    rm /etc/udev/rules.d/70-persistent-net.rules
fi

# clean apt-cache
echo "==> Cleanup apt cache"
apt-get -y autoremove --purge
apt-get -y clean
apt-get -y autoclean

# clean history
rm /home/openthinclient/.bash_history
rm /root/.bash_history

# clean logs
for i in `find /var/log/ -name "*log" -type f`
do
	>$i
done

find /var/log/ -name "*\.log\.*" -type f | xargs rm
find /var/log/ -name "*\.0" -type f | xargs rm
find /var/log/ -name "*\.[0-9]*\.gz" -type f | xargs rm

# zero out swap and mkswap again
swapSpace=$(swapon -s | tail -n 1 | awk '{print $1}')
echo $swapSpace | grep -qv Filename && (
    swapoff $swapSpace
    dd if=/dev/zero of=$swapSpace
    mkswap -f $swapSpace
)

# shrink the root fs
# are we inside a vmware guest-host?
which vmware-toolbox-cmd &> /dev/null
if [ $? -eq 0 ]; then
    echo "It seems we're inside an VMware-Guest. Will now use vmware-tools to shrink harddisc."
    vmware-toolbox-cmd disk shrink /boot
else 
    echo "No VMware tools could be found. I guess we're inside some other type of virtual host."
    echo "Do you want to reboot the system and fill your unused harddisc space with zeros?"
    echo "You'll need to do so if you want to shrink your HD. [y/N]"
    read goon
    if [ "$goon" = "y" ]; then
	grub-reboot shrink-disc-$(uname -r)
	reboot -f
    fi
fi

