#!/bin/bash
# Filename:     openthinclient-cleaner
# Purpose:      cleanup the openthinclient appliannce after initial build
#------------------------------------------------------------------------------


#------------------------------------------------------------------------------
# openthinclient specific cleanup


# make sure openthinclient server is stopped
/etc/init.d/openthinclient stop

# remove lock and log files
find /opt/openthinclient/ | grep '\.db\.lock' | xargs rm
find /opt/openthinclient/ | grep '\.log' | xargs rm

# remove nfs db
rm /opt/openthinclient/server/default/data/nfs-paths.db*

# remove homes
rm -rf 	/opt/openthinclient/server/default/data/nfs/home/*

# remove jboss stuff
rm -rf /opt/openthinclient/server/default/data/tx-object-store 
rm -rf /opt/openthinclient/server/default/data/hypersonic
rm -rf /opt/openthinclient/server/default/data/xmbean-attrs
rm -f /opt/openthinclient/server/default/data/jboss.identity

# delete ldap backups
find /var/backups/openthinclient/ -name "*\.ldiff\.*" -type f | xargs rm

# delete teamviewer config
#rm /opt/teamviewer8/config/global.conf

rm /opt/teamviewer9/config/global.conf
rm /opt/teamviewer9/config/openthinclient/client.conf
# /opt/teamviewer9/tv_bin/teamviewerd -d


#------------------------------------------------------------------------------
# general cleanup

# remove udev network rules to cleanup old interfaces
rm /etc/udev/rules.d/70-persistent-net.rules

# clean apt-cache
apt-get clean
apt-get autoremove

# clean history
rm /home/openthinclient/.bash_history
rm /root/.bash_history

# clean logs
for i in `find /var/log/ -name "*log" -type f`
do
	>$i
done

find /var/log/ -name "*\.log\.*" -type f | xargs rm
find /var/log/ -name "*\.0" -type f | xargs rm
find /var/log/ -name "*\.[0-9]*\.gz" -type f | xargs rm

# zero out swap and mkswap again
swapSpace=$(swapon -s | tail -n 1 | awk '{print $1}')
echo $swapSpace | grep -qv Filename && (
    swapoff $swapSpace
    dd if=/dev/zero of=$swapSpace
    mkswap -f $swapSpace
)

# shrink the root fs
# are we inside a vmware guest-host?
which vmware-toolbox-cmd &> /dev/null
if [ $? -eq 0 ]; then
    echo "It seems we're inside an VMware-Guest. Will now use vmware-tools to shrink harddisc."
    vmware-toolbox-cmd disk shrink /boot
else 
    echo "No VMware tools could be found. I guess we're inside some other type of virtual host."
    echo "Do you want to reboot the system and fill your unused harddisc space with zeros?"
    echo "You'll need to do so if you want to shrink your HD. [y/N]"
    read goon
    if [ "$goon" = "y" ]; then
	grub-reboot shrink-disc-$(uname -r)
	reboot -f
    fi
fi

