#!/bin/bash
# Filename:     openthinclient-ldapbackup
# Purpose:      openthinclient automatic ldap backup for the openthinclient VM
# ------------------------------------------------------------------------------

LOGGER=$(which logger)

# to have the password

Password="secret"

# define backup directory
BUDIR=/var/backups/openthinclient
[ ! -d $BUDIR ] && mkdir -p $BUDIR

# generate name of backup file
FILENAME=$BUDIR/otc-ldapbackup-`date +%d.%m.%y_%H-%M`.ldiff

ldapsearch -p 10389 -h localhost -x -b ou=openthinclient,dc=openthinclient,dc=org -D uid=admin,ou=system -w${Password} > $FILENAME || $LOGGER -p info "Automatic openthinclient LDAP backup failed"

# delete backup files older than 100 days
find $BUDIR  -mtime +100 -exec rm {} \;
