#!/bin/bash
# change openthinclient sources.lst for openthinclient VM

zenity --question --title="openthinclient edit package source" --text="Edit the sources.lst to change the default openthinclient packages\n\ \n\
 Please be careful when editing the entries for \"openthinclient\" \n\
 To continue please select yes. After that a editor will be opened \n\ \n\ 
"
# exit if the user pressed the Cancel button
if [ $? = 1 ];
then exit 0
fi

#/etc/init.d/openthinclient stop

## wait for shutdown
#{
#while lsof -i -n -P | grep 10389 &>/dev/null; do
#	sleep 1
#done
#} | zenity --progress --pulsate --auto-close --auto-kill --text="Waiting for openthinclient server shutdown..."
## woraround for proper port release
#killall nc &>/dev/null
#nc -l 0.0.0.0 10386 &
#echo ok | nc 0.0.0.0 10386

pluma /opt/openthinclient/server/default/data/nfs/root/etc/sources.list 

zenity --info --title="openthinclient edit package source" --text="Please restart openthinclient to apply the changes.\n\ \n\
 You can use the Service restart icon on the desktop for restarting the \"openthinclient\" service. \n\
Without a service restart the changes will not be applied.
"
# exit if the user pressed the Cancel button
if [ $? = 1 ];
then exit 0
fi

