#!/bin/bash
# Filename:     openthinclient-ldapbackup
# Purpose:      openthinclient automatic ldap backup for the openthinclient VM
# ------------------------------------------------------------------------------

LOGGER=$(which logger)

# get random passwod from xml file
Password=$(grep 'contextSecurityCredentials' /home/openthinclient/otc-manager-home/directory/service.xml | awk -F">" '{print $2}' | awk -F"<" '{print $1}')

# define backup directory
BUDIR=/var/backups/openthinclient
[ ! -d $BUDIR ] && mkdir -p $BUDIR

# generate name of backup file
FILENAME=$BUDIR/otc-ldapbackup-$(date +%d.%m.%y_%H-%M).ldiff

ldapsearch -H ldap://localhost:10389 -x -b ou=openthinclient,dc=openthinclient,dc=org -D uid=admin,ou=system -w"${Password}" > "$FILENAME" || "$LOGGER" -p info "Automatic openthinclient LDAP backup failed"

# delete backup files older than 100 days
find $BUDIR  -mtime +100 -exec rm {} \;
